### ISSUE TITLE
Unnecessary cache updates when sending to Symbiota

### ISSUE THREAD

**Issue by timo11** [specify/specify6#146]
When Sending to Symbiota, the cache table status is checked using the lastSendToSymbiota timestamp rather than the CacheLastUpdated timestamp, which can cause unnecessary cache updates.

**Comment by timo11** [comment]
fixed on the develop branch

**Comment by yvonneekanim** [comment]
I'm still getting an exception for the unchecked field in the jtester release and the send fails.

**Comment by yvonneekanim** [comment]
Cache table uses cacheLastUpdated timestamp when sending to Symbiota
